# ChatGPT used to guide various parts of docker compose setup
services:
  ourcity.api.prod:
    container_name: ourcity.api.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "9000:9000"
    env_file:
      - .env.production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - ourcity.postgres.prod
  ourcity.postgres.prod:
    container_name: ourcity.postgres.prod
    image: postgres:16.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ourcity
    ports:
      - "9100:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: