name: CD

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        working-directory: server
        run: docker build -f Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-backend:${{ github.sha }} .

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-backend:${{ github.sha }}

      - name: Build migration image
        working-directory: server
        run: docker build -f Dockerfile.migrate -t ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-migrate:${{ github.sha }} .

      - name: Push migration image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-migrate:${{ github.sha }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build frontend image
        working-directory: webapp
        run: docker build -f Dockerfile.prod -t ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-frontend:${{ github.sha }} .

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ourcity-frontend:${{ github.sha }}